server:
  port: 9092

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/guestdb
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
